/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaDelegate.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;
import androidx.annotation.Nullable;
import com.facebook.react.uimanager.BaseViewManagerDelegate;
import com.facebook.react.uimanager.BaseViewManagerInterface;

public class BlurhashViewManagerDelegate<T extends View, U extends BaseViewManagerInterface<T> & BlurhashViewManagerInterface<T>> extends BaseViewManagerDelegate<T, U> {
  public BlurhashViewManagerDelegate(U viewManager) {
    super(viewManager);
  }
  @Override
  public void setProperty(T view, String propName, @Nullable Object value) {
    switch (propName) {
      case "blurhash":
        mViewManager.setBlurhash(view, value == null ? null : (String) value);
        break;
      case "decodeWidth":
        mViewManager.setDecodeWidth(view, value == null ? 32 : ((Double) value).intValue());
        break;
      case "decodeHeight":
        mViewManager.setDecodeHeight(view, value == null ? 32 : ((Double) value).intValue());
        break;
      case "decodePunch":
        mViewManager.setDecodePunch(view, value == null ? 1f : ((Double) value).doubleValue());
        break;
      case "decodeAsync":
        mViewManager.setDecodeAsync(view, value == null ? false : (boolean) value);
        break;
      case "resizeMode":
        mViewManager.setResizeMode(view, (String) value);
        break;
      default:
        super.setProperty(view, propName, value);
    }
  }
}
