namespace BlurhashView {
    [default_interface]
    runtimeclass BlurhashView : Windows.UI.Xaml.Controls.UserControl{
        BlurhashView(Microsoft.ReactNative.IReactContext context);
        Windows.UI.Xaml.Controls.Image GetView();
    };
} // namespace BlurhashView