/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View} from 'react-native';
import Blurhash from 'react-native-blurhash';

const BLURHASH_ONE = 'LEHV6nWB2yk8pyo0adR*.7kCMdnj';
const BLURHASH_TWO = 'LGFFaXYk^6#M@-5c,1J5@[or[Q6.';

export default class App extends Component<{}> {
  state = {
    status: 'starting',
    message: '--',
  };
  componentDidMount() {}
  render() {
    return (
      <View style={styles.container}>
        <Blurhash
          width={300}
          height={200}
          blurhash={BLURHASH_TWO}
          punch={1}
          style={styles.blurhash}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  blurhash: {
    // Custom styling for width height etc here
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
